### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/ISMessages#1]
We need to add a bit of an inset for iPhone X, both at the top and the bottom.

**Comment by ddfreiling** [comment]
Seems to have been fixed upstream.

**Comment by EddyVerbruggen** [comment]
Fixed a while ago in https://github.com/EddyVerbruggen/ISMessages/commit/7e32dc033d95968f99b1970ef22d1d9bf2cd9f5c
