### ISSUE TITLE
insetCorrection checks crash older versions of simulator

### ISSUE THREAD

**Issue by 1andee** [EddyVerbruggen/ISMessages#2]
For users running older Xcode versions, the conditional checks to apply the iPhone X insetCorrection cause the build to crash.

The following is logged when starting Simulator 10.0 with iOS v10.3 and Xcode 8.3.3 (8E3004b):

```
/Users/ian/project/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:145:20: err
or:
      unrecognized platform name iOS
    if (@available(iOS 11.0, *)) {
                   ^
/Users/ian/project/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:148:38: err

or:
      property 'safeAreaInsets' not found on object of type 'UIWindow *'
            insetCorrection = window.safeAreaInsets.bottom;
                                     ^
/Users/ian/project/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:191:20: err
or:
      unrecognized platform name iOS
    if (@available(iOS 11.0, *)) {
                   ^
/Users/ian/project/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:194:39: err
or:
      property 'safeAreaInsets' not found on object of type 'UIWindow *'
            insetCorrection = -window.safeAreaInsets.bottom;
                                      ^
4 errors generated.
** BUILD FAILED **

Unable to apply changes on device: xxxxxx. Error is: Command xcodebuild failed
 with exit code 65.
```

When both IF statements below lines `CGFloat insetCorrection = 0;` are removed from `ISMessages/Classes/ISMessages.m` then the build compiles  successfully.

**Comment by EddyVerbruggen** [comment]
Hey Ian, thanks for the note - but frankly I don't really care about users trying to build with Xcode 8 as this library is included in a plugin that's only supposed to be used with Xcode 9 anyway.

I'm not sure whether you ended up in the correct repo by the way, this is simply a little fork of ISMessages and the upstream has fixed the iPhone X inset in the meanwhile ;)

**Comment by 1andee** [comment]
Hey @EddyVerbruggen, definitely the correct repo as I'm using the nativescript-feedback dependency. Thanks anyways for your feedback.

**Comment by EddyVerbruggen** [comment]
Ah nice! I hope you can update to Xcode 9 then. Shouldn’t need to run iOS11 though. Although the default sims will be iOS11 with Xcode 9 of course.
